export const QUERY_KEY = {
	NOW_PLAY: 'NOW_PLAY',
	INFINITE_NOW_PLAY: 'INFINITE_NOW_PLAY',
	INFINITE_UPCOMING: 'INFINITE_UPCOMING',
	INFINITE_TOPRATED: 'INFINITE_TOPRATED',
	GET_CATEGORY: 'GET_CATEGORY',
	GET_DETAIL: 'GET_DETAIL',
	GET_TRAILER: 'GET_TRAILER',
	INFINITE_SEARCH: 'INFINITE_SEARCH',
};
