export const QUERY_KEY = {
	NOW_PLAYING: 'NOW_PLAYING',
	TOP_RATED: 'TOP_RATED',
	UP_COMING: 'UP_COMING',
	GET_DETAIL: 'GET_DETAIL',
	GET_VIDEO: 'GET_VIDEO',
	POPULAR: 'POPULAR',
	INFINITE_NOW_PLAY: 'INFINITE_NOW_PLAY',
	INFINITE_TOPRATED: 'INFINITE_TOPRATED',
	INFINITE_UPCOMING: 'INFINITE_UPCOMING',
	INFINITE_SEARCH: 'INFINITE_SEARCH',
};
